--LEFT JOIN OF STRESS AND SLEEP TABLES 
SELECT SLEEP.DATE, STRESS, SLEEP
FROM SLEEP 
LEFT JOIN STRESS 
ON SLEEP.DATE = STRESS.DATE;
--RIGHT JOIN OF RHR AND BODY_BATTERY 
SELECT DISTINCT(RHR.DATE), RESTING_HEART_RATE,BODY_BATTERY, MAX_VALUE
FROM RHR 
RIGHT JOIN BODY_BATTERY 
ON RHR.DATE = BODY_BATTERY.DATE
ORDER BY DATE;
